---
- hosts: localhost
  tasks:
  - name: "Downloading Forge Mod"
    get_url:
      url: https://getbukkit.org/get/92f15442e8a9edea8394b208ac08d667
      dest: "{{app_dir}}/download/craftbukkit-1.18.2.jar"
      mode: '0750'