---
- hosts: localhost
  tasks:
  - name: "Making directory"
    shell: "mkdir -p {{app_dir}}/logs {{app_dir}}/minecraft"
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/minecraft/eula.txt"
      content: |
        eula=true
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/minecraft/server.properties"
      content: |
        server-port=3074
        rcon.port=3075
        query.port=3076
        rcon.password=Crafter9000
        enable-rcon=true
        level-name=world
        motd=Welcome to Storm's Minecraft Server!
        max-players=20
        level-seed=2976643220357667859
  - name: "Downloading minecraft"
    get_url:
      url: https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar
      dest: "{{app_dir}}/minecraft/server.jar"
      mode: '0750'
  - name: "Make sure you update your memory requirements {{app_dir}}/conf/minecraft.conf"
    shell: echo "I'm just a comment"


