---
- hosts: localhost
  tasks:
  - name: "Backing up minecraft server.jar"
    shell: "mv {{app_dir}}/minecraft/server.jar {{app_dir}}/minecraft/server.jar.old"
  - name: "Downloading Paper Latest"
    get_url:
      url: https://api.papermc.io/v2/projects/paper/versions/latest/builds/81/downloads/paper-1.21.3-81.jar
      dest: "{{app_dir}}/minecraft/paper.jar"
      mode: '0750'
  - name: "Installing Paper Latest"
    shell: "cd {{app_dir}}/minecraft/ && java -jar {{app_dir}}/minecraft/paper.jar"
  - name: "Changing Paper Latest"
    shell: "mv {{app_dir}}/minecraft/paper.jar {{app_dir}}/minecraft/server.jar"
  - name: "Start your minecraft server and you will see plugins folder {{app_dir}}/minecraft/plugins/"
    shell: echo "I'm just a comment"
