---
- hosts: localhost
  tasks:
  - name: "Stopping Minecraft Server!"
    shell: ps aux | grep -ie "server.jar" | grep -v grep | awk '{print $2}' | xargs kill -9
  - name: "Start Minecraft :: Log: {{app_dir}}/logs/minecraft-console.log"
    shell: cd {{app_dir}}/minecraft/ && nohup java -Xmx{{max_memory}}M -Xms{{min_memory}}M -jar {{app_dir}}/minecraft/server.jar --nogui >> {{app_dir}}/logs/minecraft-console.log 2>&1&
